kind: BuildConfig
apiVersion: v1
metadata:
  name: angular-configmap
spec:
  source:
    git: 
      uri: https://github.com/adambkaplan/angular-configmap.git
      ref: master
    configMaps:
      - configMap:
          name: angular-env
        destinationDir: config/environments
  strategy:
    dockerStrategy: 
      env:
        - name: NG_CONFIG
          value: origin
        - name: BUILD_LOGLEVEL
          value: "5"
  output:
    to:
      kind: ImageStreamTag
      name: "angular-configmap:latest"
